[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = ["targets/x86.json"]
rustflags = ["-Csoft-float=yes", "-Crelocation-model=static"]
